
// School Actions
export const SET_SCHOOL_ADMIN = 'SET_SCHOOL_ADMIN';
export const INITIALIZE_DASHBOARD_DATA = 'INITIALIZE_DASHBOARD_DATA';
export const BUS_STATS_CHANGED = 'BUS_STATS_CHANGED';
export const LOAD_SCHOOL_ADMINS = 'LOAD_SCHOOL_ADMINS';




// Church Actions
export const SET_CHURCH_ADMIN = 'SET_CHURCH_ADMIN';
export const INITIALIZE_CHURCH_DASHBOARD = 'INITIALIZE_CHURCH_DASHBOARD';
export const LOAD_BUS_DATA = 'LOAD_BUS_DATA';
